#include <nrfx.h>
#include <uicr/uicr.h>

#define CONF_MOD uicr_periphconf_table

/* Owned peripherals:
 *   #0: 0x5f9c6000 [S, DMA-S, IRQ->RADIOCORE]
 */
UICR_IRQMAP_IRQ_SINK_SET(CONF_MOD, NRFX_IRQ_NUMBER_GET(0x5f09c600), NRF_PROCESSOR_RADIOCORE);

/* IPC mapping:
 *   #0: RADIOCORE ch2 -> GLOBAL_SLOW ch2
 *   #1: GLOBAL_SLOW ch0 -> RADIOCORE ch0
 *   #2: GLOBAL_SLOW ch2 -> RADIOCORE ch2
 */
UICR_IPCMAP_CHANNEL_CFG(CONF_MOD, 0, NRF_DOMAIN_RADIOCORE, 2, NRF_DOMAIN_GLOBALSLOW, 2);
UICR_IPCMAP_CHANNEL_CFG(CONF_MOD, 1, NRF_DOMAIN_GLOBALSLOW, 0, NRF_DOMAIN_RADIOCORE, 0);
UICR_IPCMAP_CHANNEL_CFG(CONF_MOD, 2, NRF_DOMAIN_GLOBALSLOW, 2, NRF_DOMAIN_RADIOCORE, 2);

#define TMP_PPIB130 (0x5f925000UL)
#define TMP_PPIB133 (0x5f99d000UL)

/* DPPIC#0 @ 0x5f922000 (DPPIC130)
 *   source channels: 3
 *   sink channels: 0, 2
 */
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(CONF_MOD, TMP_PPIB130, 11);
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(CONF_MOD, TMP_PPIB130, 8);
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(CONF_MOD, TMP_PPIB130, 10);

/* DPPIC#1 @ 0x5f991000 (DPPIC132)
 *   source channels: 0, 2
 *   sink channels: 3
 */
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(CONF_MOD, TMP_PPIB133, 0);
UICR_PPIB_SUBSCRIBE_SEND_ENABLE(CONF_MOD, TMP_PPIB133, 2);
UICR_PPIB_PUBLISH_RECEIVE_ENABLE(CONF_MOD, TMP_PPIB133, 3);
