/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_MISC_NORDIC_NRF_SPU_V2_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_MISC_NORDIC_NRF_SPU_V2_H_

#define NRF_SPU_FEATURE_IPCT_CHANNEL        (0)
#define NRF_SPU_FEATURE_IPCT_INTERRUPT      (1)
#define NRF_SPU_FEATURE_DPPIC_CHANNEL       (2)
#define NRF_SPU_FEATURE_DPPIC_CHANNEL_GROUP (3)
#define NRF_SPU_FEATURE_GPIOTE_CHANNEL      (4)
#define NRF_SPU_FEATURE_GPIOTE_INTERRUPT    (5)
#define NRF_SPU_FEATURE_GPIO_PIN            (6)
#define NRF_SPU_FEATURE_GRTC_CC             (7)
#define NRF_SPU_FEATURE_GRTC_PWMCONFIG      (8)
#define NRF_SPU_FEATURE_GRTC_CLK            (9)
#define NRF_SPU_FEATURE_GRTC_SYSCOUNTER     (10)
#define NRF_SPU_FEATURE_GRTC_INTERRUPT      (11)
#define NRF_SPU_FEATURE_MRAMC_WAITSTATES    (12)
#define NRF_SPU_FEATURE_MRAMC_AUTOPOWERDOWN (13)
#define NRF_SPU_FEATURE_MRAMC_READY         (14)
#define NRF_SPU_FEATURE_BELLS_PROCESSOR     (15)
#define NRF_SPU_FEATURE_BELLS_EVENTS        (16)
#define NRF_SPU_FEATURE_BELLS_INTERRUPT     (17)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_MISC_NORDIC_NRF_SPU_V2_H_ */
