/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 * SPDX-License-Identifier: Apache-2.0
 */

#include <uicr/uicr.h>
#include <zephyr/toolchain.h>
#include <zephyr/sys/util.h>

#if defined(CONFIG_NRF_HALTIUM_UICR_PERIPHCONF)
#include <uicr_periphconf_params.h>
#endif

#define UNSET_VALUE    UICRV2_LOCK_PALL_Unlocked
#define DISABLED_VALUE UNSET_VALUE
#define ENABLED_VALUE  UICRV2_LOCK_PALL_Locked

#define CONF_ENABLE_IF(_sym)        COND_CODE_1(IS_ENABLED(_sym), (ENABLED_VALUE), (DISABLED_VALUE))
#define CONF_VALUE_IF(_sym, _value) COND_CODE_1(IS_ENABLED(_sym), (_value), (UNSET_VALUE))

Z_GENERIC_SECTION("nrf_haltium_uicr")
__used NRF_UICRV2_Type nrf_haltium_uicr_structure = {
	.VERSION = UNSET_VALUE,
	.RESERVED = UNSET_VALUE,
	.LOCK = CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_LOCK),
	.RESERVED1 = UNSET_VALUE,
	.APPROTECT =
		{
			.APPLICATION = CONF_ENABLE_IF(
				CONFIG_NRF_HALTIUM_UICR_APPROTECT_APPLICATION_PROTECT),
			.RADIOCORE =
				CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_APPROTECT_RADIOCORE_PROTECT),
			.RESERVED = UNSET_VALUE,
			.CORESIGHT =
				CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_APPROTECT_CORESIGHT_PROTECT),
		},
	.ERASEPROTECT = CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_ERASEPROTECT),
	.PROTECTEDMEM =
		{
			.ENABLE = CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_PROTECTEDMEM),
			.SIZE4KB = CONF_VALUE_IF(CONFIG_NRF_HALTIUM_UICR_PROTECTEDMEM,
						 CONFIG_NRF_HALTIUM_UICR_PROTECTEDMEM_SIZE / KB(4)),
		},
	.RESERVED2 = {UNSET_VALUE, UNSET_VALUE, UNSET_VALUE},
	.ITS =
		{
			.ENABLE = CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_ITS),
			.ADDRESS = CONF_VALUE_IF(CONFIG_NRF_HALTIUM_UICR_ITS,
						 CONFIG_NRF_HALTIUM_UICR_ITS_ADDRESS),
			.APPLICATIONSIZE =
				CONF_VALUE_IF(CONFIG_NRF_HALTIUM_UICR_ITS,
					      CONFIG_NRF_HALTIUM_UICR_ITS_APPLICATION_SIZE),
			.RADIOCORESIZE = CONF_VALUE_IF(CONFIG_NRF_HALTIUM_UICR_ITS,
						       CONFIG_NRF_HALTIUM_UICR_ITS_RADIOCORE_SIZE),
		},
	.RESERVED3 = {UNSET_VALUE, UNSET_VALUE, UNSET_VALUE, UNSET_VALUE, UNSET_VALUE, UNSET_VALUE,
		      UNSET_VALUE, UNSET_VALUE},
	.PERIPHCONF =
		{
			.ENABLE = CONF_ENABLE_IF(CONFIG_NRF_HALTIUM_UICR_PERIPHCONF),
			.ADDRESS = CONF_VALUE_IF(CONFIG_NRF_HALTIUM_UICR_PERIPHCONF,
						 GEN_UICR_PERIPHCONF_ADDRESS),
			.COUNT = CONF_VALUE_IF(CONFIG_NRF_HALTIUM_UICR_PERIPHCONF,
					       GEN_UICR_PERIPHCONF_SIZE /
						       sizeof(struct uicr_periphconf_entry)),
		},
	.MPCCONF =
		{
			.ENABLE = UNSET_VALUE,
			.ADDRESS = UNSET_VALUE,
			.COUNT = UNSET_VALUE,
		},
};
